### PR TITLE
expand if contentSize of scrollView changes and is not sufficiently long

### PR DESCRIPTION
**Pull request by griddle**
Hi @Mazyod,

This is PR to fix https://github.com/telly/TLYShyNavBar/issues/53. 

I'm not familiar with what's required to have an approved PR so please let me know. I figured I'd create it and go from there.

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks a lot for this @griddle. The code looks great. I would personally use `void *blah = &blah;`, since that eliminates the need to use dereferencing everywhere `&`, and looks cool.

But in any case, I am worried about existing apps that might, for any reason, deallocate the scrollView without cleaning up the `scrollView` property on the `TLYShyNavBarManager`. That will make us lose access to the observer...

How about changing the `scrollView` property to strong? I understand it might unnecessarily cause the `scrollView` to hang around for longer than it is needed, but at least it won't cause a crash.

**Comment by Mazyod** [comment]
Also, if you don't mind me being super picky, the method you defined defeats the purpose of using `BOOL scrollViewIsSuffecientlyLong` variable. That was purely used as self-documenting code, but the function you defined takes care of that now. So, returning the result immediately should win us one less line of code :computer: :gun:

**Comment by griddle** [comment]
Thanks @Mazyod. Understood, I'll make the changes when I have a bit of time today and send them your way.

> the method you defined defeats the purpose of using BOOL scrollViewIsSuffecientlyLong variable

I was totally going to do that and then didn't. :+1:

**Comment by griddle** [comment]
@Mazyod I went ahead and made the changes, please let me know if there's anything else

**Comment by Mazyod** [comment]
:pray: ほんとに ありがと ございます

:shipit: !

**Pull request merged**
