### PR TITLE
calculateTotalHeightRecursively should return the current height, not the height when fully expanded

### LINKED ISSUE #141: Extension view flickering issue
Hello, I've encountered issues with extension view when there are certain amount of cells in table view (approximately view.frame.height/cell.frame height + 1).
It is easy to reproduce in demo setting number of rows to 16

How it looks:
ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by ndrewh**
Fixes #141.

### CODE REVIEW

**Comment by floriankrueger** [comment]
Hi, just wanted to catch up on this PR. We have the fix in production for more than a month now (via https://github.com/t089/TLYShyNavBar) and have had no issues so far. Would you consider merging it so that we can move back from the fork to the original repo? thank you!

**Comment by Mazyod** [comment]
Thanks for the fix and the confirmation. I'll test this today with better demo cases and merge. If all goes well, we'll have a new release, as well!

**Comment by Mazyod** [comment]
Seems legit! I will need to add new test cases to the demo later, to properly test everything, then hopefully make a new release

**Comment by floriankrueger** [comment]
Any updates on the release? We'd love to remove our fork and go back to the original repo 🙂

**Pull request merged**
