### PR TITLE
Adding support for sticky nav bar

### PR DESCRIPTION
**Pull request by TiagoVeloso**

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks for the PR! I see a few issues with the implementation, I will need to evaluate more. In all cases, I'll be sure to get back.

**Comment by TiagoVeloso** [comment]
I've pushed a fix, I think I was breaking something.

**Comment by Mazyod** [comment]
Thanks again, @TiagoVeloso. I still thought there were some fundamentally wrong pieces of code, and it isn't your fault. Looking at the code, I found unused code, and some really convoluted approaches.

I fixed all that, and when I did, supporting your feature request was as simple as setting `stick` to `YES` on the `TLYShyViewController`!

So, closing this in favor of #89

**Comment by TiagoVeloso** [comment]
All good mate. :)

**Pull request closed without merging**
