### PR TITLE
Add ability to stick extension view to the top.

### PR DESCRIPTION
**Pull request by modastic**
Add ability to stick extension view to the top and not disappear with the navigation bar.

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks for the PR! I will take a look at it, but I can't merge it with the xccheckout file changes, because they are irrelevant.

I would also appreciate it if you can expand on the Readme file, so new users are aware of the feature. Adding a gif like the ones present would be awesome!

**Comment by modastic** [comment]
No problem, I took out the xccheckout file changes and updated the read me file.

**Comment by Mazyod** [comment]
Awesome! That was fast.
I'll try to hold up my end of the bargain, then.

**Comment by Mazyod** [comment]
Sorry it took me so long, will update the podspec as well, this needs a new release.

**Pull request merged**
