### PR TITLE
Try to handle contentInset on scroll

### PR DESCRIPTION
**Pull request by DagAgren**
Here's an attempt to clean up and fix the various patches in issue 30. I don't know if it works perfectly, since this is such an awkward operation, but I've tried to include most of the things suggested by different users, and corrected it to calculate things properly.

You probably have a better idea of how to simplify it or make it make more sense, though.

### CODE REVIEW

**Comment by Mazyod** [comment]
Really appreciate you opening this. Indeed, there are some subtle ways to improve the implementation, but nothing major. I think the basic idea is sane .. However, would like to take a :hocho: at it myself and see what comes out.

_ETA: 2 weeks_

**Comment by DagAgren** [comment]
Yeah, with a tricky piece of code like this, you really want to have a good grip on every part of the code or it will fall apart real quick. I'll use this in the meanwhile until you can put something together.

**Comment by Mazyod** [comment]
OK, finally got around to this. By running the demo, I can see the component not in perfect condition. The best way to approach this is to build on top of the existing "drawer" system (see readme). Notice how the sticky extension view follows the navbar religiously? We need to create a similar relationship between the scrollView and the extension view.

I am looking for ways to do that, and hopefully give you more details. Do you think you're up that?

**Comment by Mazyod** [comment]
This should finally be resolved in v1.0.0. Thanks @DagAgren !

**Pull request closed without merging**
